### ISSUE TITLE
“厶”部件平衡问题

### ISSUE THREAD

**Issue by zhenlige** [lxgw/LxgwWenkaiGB#3]
如图，有点倾斜的感觉，可能是砍掉断笔后未经调整造成

![图片](https://user-images.githubusercontent.com/38127204/234023814-2d14ed54-c2b6-4d43-9a09-8fab6e7b37a8.png)

**Comment by lxgw** [comment]
这个「厶」部件取自「芫荽」。后续视情况调整。

**Comment by aikahiiragi** [comment]
其實原版（允許折筆/露芒）就平衡了。
個人覺得連一點折筆都不允許是太病態的。

**Comment by zhenlige** [comment]
这是手写风格，一般人手写不会断开写，除非刻意模仿刻版风格


> 其實原版（允許折筆/露芒）就平衡了。 個人覺得連一點折筆都不允許是太病態的。

**Comment by zhenlige** [comment]
而且此字体另有原版笔画风格的非GB版

**Comment by aikahiiragi** [comment]
> 这是手写风格，一般人手写不会断开写，除非刻意模仿刻版风格
> 
> > 其實原版（允許折筆/露芒）就平衡了。 個人覺得連一點折筆都不允許是太病態的。

也不見得，例如寫顏體其實就是斷開寫的。而顏字有不少人小學就開始學。
