### ISSUE TITLE
可否提供打了nerd font图标补丁的版本？

### ISSUE THREAD

**Issue by lovelock** [lxgw/LxgwWenkaiGB#4]
您好，我用了两天这个字体觉得很不错，希望可以在终端环境下使用，但很多图标缺失导致没办法用。所以希望能给mono字体打上https://www.nerdfonts.com/ 补丁，适合在终端使用。谢谢。

之所以我不自己打是因为这个打补丁用的脚本貌似存在内存问题，不管我在16G还是32G的机器上都不能执行完成。

**Comment by lxgw** [comment]
非常抱歉，无此计划。

**Comment by zryyyy** [comment]
> 您好，我用了两天这个字体觉得很不错，希望可以在终端环境下使用，但很多图标缺失导致没办法用。所以希望能给mono字体打上https://www.nerdfonts.com/ 补丁，适合在终端使用。谢谢。
> 
> 之所以我不自己打是因为这个打补丁用的脚本貌似存在内存问题，不管我在16G还是32G的机器上都不能执行完成。

你好，我在我的仓库 [zryyyy/Nerd-Font-Patcher](https://github.com/zryyyy/Nerd-Font-Patcher) 里放了一个补丁字体的 Github Actions。你可以 fork 一下我的仓库上传你想要补丁的字体文件，然后运行一下 Fonts Patcher 这个脚本就可以了

**Comment by lovelock** [comment]
> > 您好，我用了两天这个字体觉得很不错，希望可以在终端环境下使用，但很多图标缺失导致没办法用。所以希望能给mono字体打上https://www.nerdfonts.com/ 补丁，适合在终端使用。谢谢。
> > 之所以我不自己打是因为这个打补丁用的脚本貌似存在内存问题，不管我在16G还是32G的机器上都不能执行完成。
> 
> 你好，我在我的仓库 [zryyyy/Nerd-Font-Patcher](https://github.com/zryyyy/Nerd-Font-Patcher) 里放了一个补丁字体的 Github Actions。你可以 fork 一下我的仓库上传你想要补丁的字体文件，然后运行一下 Fonts Patcher 这个脚本就可以了

我后来在本地patch上了，但写代码看着费劲，已经不想用了。。。不过你这个想法挺好，试了下你打包的字体，确实可以用

**Comment by zryyyy** [comment]
> > > 您好，我用了两天这个字体觉得很不错，希望可以在终端环境下使用，但很多图标缺失导致没办法用。所以希望能给mono字体打上https://www.nerdfonts.com/ 补丁，适合在终端使用。谢谢。
> > > 之所以我不自己打是因为这个打补丁用的脚本貌似存在内存问题，不管我在16G还是32G的机器上都不能执行完成。
> > 
> > 
> > 你好，我在我的仓库 [zryyyy/Nerd-Font-Patcher](https://github.com/zryyyy/Nerd-Font-Patcher) 里放了一个补丁字体的 Github Actions。你可以 fork 一下我的仓库上传你想要补丁的字体文件，然后运行一下 Fonts Patcher 这个脚本就可以了
> 
> 我后来在本地patch上了，但写代码看着费劲，已经不想用了。。。不过你这个想法挺好，试了下你打包的字体，确实可以用

我现在感觉苹方是真好看😂

**Comment by lovelock** [comment]
> > > > 您好，我用了两天这个字体觉得很不错，希望可以在终端环境下使用，但很多图标缺失导致没办法用。所以希望能给mono字体打上https://www.nerdfonts.com/ 补丁，适合在终端使用。谢谢。
> > > > 之所以我不自己打是因为这个打补丁用的脚本貌似存在内存问题，不管我在16G还是32G的机器上都不能执行完成。
> > > 
> > > 
> > > 你好，我在我的仓库 [zryyyy/Nerd-Font-Patcher](https://github.com/zryyyy/Nerd-Font-Patcher) 里放了一个补丁字体的 Github Actions。你可以 fork 一下我的仓库上传你想要补丁的字体文件，然后运行一下 Fonts Patcher 这个脚本就可以了
> > 
> > 
> > 我后来在本地patch上了，但写代码看着费劲，已经不想用了。。。不过你这个想法挺好，试了下你打包的字体，确实可以用
> 
> 我现在感觉苹方是真好看😂

在这方面你可以相信苹果的审美
