### ISSUE TITLE
缺少全角单引号和双引号

### ISSUE THREAD

**Issue by Kokouki** [lxgw/LxgwWenkaiGB#7]
缺少全角单引号和双引号，无论中英文输入单引号、双引号都是半角的。按照中文习惯，应该是全角的。

**Comment by lxgw** [comment]
抱歉，此前收到用户反馈，如果引号为全宽，`，“` `：“` `”。` 间会存在较大的空隙，此外`It’s`等也会出现空隙，所以并没有将`“”`做成全宽，请您谅解。
