### ISSUE TITLE
建议删除字体的emoji

### ISSUE THREAD

**Issue by Achuan-2** [lxgw/LxgwWenkaiGB#8]
尤其现在win11的emoji在微软系软件变得很Q，字体自带的emoji覆盖就会很奇怪
![Clip_2024-03-06_10-01-10](https://github.com/lxgw/LxgwWenkaiGB/assets/60436214/4b381e33-4e95-479d-a89d-01d40d24571e)

**Comment by lxgw** [comment]
Klee One 自带的一些 Emoji 字符，文楷予以保留。

除此之外，尽量不会新增 Emoji 字符。
